name: Deploying to GCE

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: check out code
      use: actions/checkout@v3 

    - name: authenticate with gcp
      use: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CRED }}

    - name: setting up gcloud cli
      use: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.proj_id }}
        export_default_credentials: true

    - name: copy command
      run: |
        gcloud compute scp --recursive . linen-hwak:/home/roshan/yt_stuff/
     

